[package]
name = "adventofcode2017"
version = "0.1.0"
authors = ["Alexander Kjäll <alexander.kjall@gmail.com>"]

[dependencies]

[[bin]]
name = "day_1"
path = "src/day_1.rs"

[[bin]]
name = "day_2"
path = "src/day_2.rs"

[[bin]]
name = "day_3"
path = "src/day_3.rs"
